# Generated by Django 5.2.7 on 2025-10-16 00:35

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('quiz', 'Quiz'), ('upload', 'Upload de Arquivo'), ('forum', 'Fórum de Discussão'), ('video', 'Vídeo Interativo'), ('anotacao', 'Anotação'), ('prova', 'Prova Opcional')], max_length=20)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('finalizada', 'Finalizada')], default='ativa', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('gerada_por_ia', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAtividade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('quiz', 'Quiz'), ('upload', 'Upload de Arquivo'), ('forum', 'Fórum de Discussão'), ('video', 'Vídeo Interativo'), ('anotacao', 'Anotação'), ('prova', 'Prova Opcional')], max_length=20)),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('inativa', 'Inativa'), ('finalizada', 'Finalizada')], default='ativa', max_length=20)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('gerada_por_ia', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical atividade',
                'verbose_name_plural': 'historical atividades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalQuestaoBanco',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('area', models.CharField(max_length=50)),
                ('dificuldade', models.CharField(max_length=20)),
                ('resposta_correta', models.TextField()),
                ('opcoes', models.JSONField(default=list)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical questao banco',
                'verbose_name_plural': 'historical questao bancos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRespostaAtividade',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('nota', models.FloatField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical resposta atividade',
                'verbose_name_plural': 'historical resposta atividades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='QuestaoBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('area', models.CharField(max_length=50)),
                ('dificuldade', models.CharField(max_length=20)),
                ('resposta_correta', models.TextField()),
                ('opcoes', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('nota', models.FloatField(blank=True, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
